#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using System.Collections.Generic;
using Everlong.Globalization;

namespace Everlong.Nester.Extensions.Properties;

/// <summary>
/// This class was generated by <c>dotnet elg gen</c>.
/// <para>Usage:</para>
/// <list type="bullet">
/// <item><description>Update strings in the JSON files under locale subdirectories.</description></item>
/// <item><description>Add a locale by creating a new subdirectory (for example <c>zh-CN\</c>) with matching JSON files.</description></item>
/// <item><description>Regenerate by running <c>dotnet elg gen</c> from the project directory.</description></item>
/// <item><description>Configuration file: <c>Properties\i18n\i18n.json</c>.</description></item>
/// <item><description>Do not edit generated files manually; they are overwritten on next generation.</description></item>
/// </list>
/// </summary>
public static partial class Lang
{
  public static readonly LangProvider Provider = new(Locales.En);

  public static ILangManifest Manifest { get; } = new LangManifestImpl();

  internal static DialogStrings Dialog { get; } = new DialogStrings(Provider);

  public static class Locales
  {
    public static readonly IStringProvider En = new DictionaryStringProvider(new Dictionary<string, string>
    {
      ["Everlong.Nester.Dialog.Alert.ButtonText"] = "OK",
      ["Everlong.Nester.Dialog.Alert.Title"] = "Alert",
      ["Everlong.Nester.Dialog.Choice.CancelText"] = "Cancel",
      ["Everlong.Nester.Dialog.Choice.PrimaryText"] = "Yes",
      ["Everlong.Nester.Dialog.Choice.SecondaryText"] = "No",
      ["Everlong.Nester.Dialog.Choice.Title"] = "Choose",
      ["Everlong.Nester.Dialog.Close"] = "Close",
      ["Everlong.Nester.Dialog.ColorPicker.ConfirmText"] = "Confirm",
      ["Everlong.Nester.Dialog.ColorPicker.Message"] = "Adjust channel values to select a color",
      ["Everlong.Nester.Dialog.ColorPicker.ResetText"] = "Reset",
      ["Everlong.Nester.Dialog.ColorPicker.Title"] = "Select Color",
      ["Everlong.Nester.Dialog.Confirm.CancelText"] = "Cancel",
      ["Everlong.Nester.Dialog.Confirm.ConfirmText"] = "Yes",
      ["Everlong.Nester.Dialog.Confirm.Title"] = "Confirm",
      ["Everlong.Nester.Dialog.DateTimePicker.ConfirmText"] = "Confirm",
      ["Everlong.Nester.Dialog.DateTimePicker.DayLabel"] = "Day",
      ["Everlong.Nester.Dialog.DateTimePicker.HourLabel"] = "Hour",
      ["Everlong.Nester.Dialog.DateTimePicker.InvalidInput"] = "Invalid date/time input",
      ["Everlong.Nester.Dialog.DateTimePicker.Message"] = "Enter date and time",
      ["Everlong.Nester.Dialog.DateTimePicker.MinuteLabel"] = "Minute",
      ["Everlong.Nester.Dialog.DateTimePicker.MonthLabel"] = "Month",
      ["Everlong.Nester.Dialog.DateTimePicker.NowText"] = "Now",
      ["Everlong.Nester.Dialog.DateTimePicker.RangeHintFormat"] = "Range: {min} - {max}",
      ["Everlong.Nester.Dialog.DateTimePicker.SecondLabel"] = "Second",
      ["Everlong.Nester.Dialog.DateTimePicker.Title"] = "Select Date and Time",
      ["Everlong.Nester.Dialog.DateTimePicker.UnlimitedRange"] = "Range: Unlimited",
      ["Everlong.Nester.Dialog.DateTimePicker.YearLabel"] = "Year",
      ["Everlong.Nester.Dialog.ImagePreview.BytesSourceDisplayFormat"] = "Memory Data ({count} bytes)",
      ["Everlong.Nester.Dialog.ImagePreview.LoadFailedError"] = "Failed to load image",
      ["Everlong.Nester.Dialog.ImagePreview.LoadingStatus"] = "Loading image...",
      ["Everlong.Nester.Dialog.ImagePreview.NextText"] = "Next",
      ["Everlong.Nester.Dialog.ImagePreview.NoHttpClientError"] = "Cannot load network image: HttpClient not provided. Please pass it through ImagePreviewInput.HttpClient.",
      ["Everlong.Nester.Dialog.ImagePreview.PreviousText"] = "Previous",
      ["Everlong.Nester.Dialog.ImagePreview.Title"] = "Image Preview",
      ["Everlong.Nester.Dialog.Ipv4.BackspaceToolTip"] = "Backspace",
      ["Everlong.Nester.Dialog.Ipv4.ClearText"] = "Clear",
      ["Everlong.Nester.Dialog.Ipv4.ConfirmText"] = "Confirm",
      ["Everlong.Nester.Dialog.Ipv4.Message"] = "Please enter an IPv4 address",
      ["Everlong.Nester.Dialog.Ipv4.PingBadRouteReason"] = "Bad route",
      ["Everlong.Nester.Dialog.Ipv4.PingFailedFormat"] = "Ping failed ({reason})",
      ["Everlong.Nester.Dialog.Ipv4.PingHostUnreachableReason"] = "Host unreachable",
      ["Everlong.Nester.Dialog.Ipv4.PingNetworkUnreachableReason"] = "Network unreachable",
      ["Everlong.Nester.Dialog.Ipv4.PingPacketTooBigReason"] = "Packet too big",
      ["Everlong.Nester.Dialog.Ipv4.PingPortUnreachableReason"] = "Port unreachable",
      ["Everlong.Nester.Dialog.Ipv4.PingProtocolUnreachableReason"] = "Protocol unreachable",
      ["Everlong.Nester.Dialog.Ipv4.PingSuccessFormat"] = "Ping succeeded ({time} ms)",
      ["Everlong.Nester.Dialog.Ipv4.PingText"] = "Ping Test",
      ["Everlong.Nester.Dialog.Ipv4.PingTimedOutReason"] = "Timed out",
      ["Everlong.Nester.Dialog.Ipv4.PingTtlExpiredReason"] = "TTL expired",
      ["Everlong.Nester.Dialog.Ipv4.PingUnavailableError"] = "Ping unavailable",
      ["Everlong.Nester.Dialog.Ipv4.PingUnknownReason"] = "Unknown error",
      ["Everlong.Nester.Dialog.Ipv4.Title"] = "Enter IP Address",
      ["Everlong.Nester.Dialog.Numpad.BackspaceToolTip"] = "Backspace",
      ["Everlong.Nester.Dialog.Numpad.ClearToolTip"] = "Clear",
      ["Everlong.Nester.Dialog.Numpad.ConfirmText"] = "Confirm",
      ["Everlong.Nester.Dialog.Numpad.InvalidExpressionError"] = "Invalid expression",
      ["Everlong.Nester.Dialog.Numpad.Message"] = "",
      ["Everlong.Nester.Dialog.Numpad.OutOfRangeWarningFormat"] = "Result out of range: {range}",
      ["Everlong.Nester.Dialog.Numpad.RangeHintFormat"] = "Range: {min} - {max}{step}",
      ["Everlong.Nester.Dialog.Numpad.ResultHintFormat"] = "= {value}{suffix}",
      ["Everlong.Nester.Dialog.Numpad.ResultHintInvalid"] = "= ?",
      ["Everlong.Nester.Dialog.Numpad.Title"] = "Input number",
      ["Everlong.Nester.Dialog.OptionSelect.Title"] = "Select",
      ["Everlong.Nester.Dialog.SignaturePad.ClearText"] = "Clear",
      ["Everlong.Nester.Dialog.SignaturePad.ConfirmText"] = "Confirm",
      ["Everlong.Nester.Dialog.SignaturePad.Message"] = "Please sign in the area below to confirm",
      ["Everlong.Nester.Dialog.SignaturePad.StrokeCountFormat"] = "Signed strokes: {count}",
      ["Everlong.Nester.Dialog.SignaturePad.Title"] = "Signature Pad",
    });
    public static readonly IStringProvider ZhHansCn = new DictionaryStringProvider(new Dictionary<string, string>
    {
      ["Everlong.Nester.Dialog.Alert.ButtonText"] = "确定",
      ["Everlong.Nester.Dialog.Alert.Title"] = "提示",
      ["Everlong.Nester.Dialog.Choice.CancelText"] = "取消",
      ["Everlong.Nester.Dialog.Choice.PrimaryText"] = "是",
      ["Everlong.Nester.Dialog.Choice.SecondaryText"] = "否",
      ["Everlong.Nester.Dialog.Choice.Title"] = "选择",
      ["Everlong.Nester.Dialog.Close"] = "关闭",
      ["Everlong.Nester.Dialog.ColorPicker.ConfirmText"] = "确认",
      ["Everlong.Nester.Dialog.ColorPicker.Message"] = "调整通道值以选择颜色",
      ["Everlong.Nester.Dialog.ColorPicker.ResetText"] = "重置",
      ["Everlong.Nester.Dialog.ColorPicker.Title"] = "选择颜色",
      ["Everlong.Nester.Dialog.Confirm.CancelText"] = "取消",
      ["Everlong.Nester.Dialog.Confirm.ConfirmText"] = "是",
      ["Everlong.Nester.Dialog.Confirm.Title"] = "确认",
      ["Everlong.Nester.Dialog.DateTimePicker.ConfirmText"] = "确认",
      ["Everlong.Nester.Dialog.DateTimePicker.DayLabel"] = "日",
      ["Everlong.Nester.Dialog.DateTimePicker.HourLabel"] = "时",
      ["Everlong.Nester.Dialog.DateTimePicker.InvalidInput"] = "日期/时间输入无效",
      ["Everlong.Nester.Dialog.DateTimePicker.Message"] = "输入日期和时间",
      ["Everlong.Nester.Dialog.DateTimePicker.MinuteLabel"] = "分",
      ["Everlong.Nester.Dialog.DateTimePicker.MonthLabel"] = "月",
      ["Everlong.Nester.Dialog.DateTimePicker.NowText"] = "现在",
      ["Everlong.Nester.Dialog.DateTimePicker.RangeHintFormat"] = "范围：{min} - {max}",
      ["Everlong.Nester.Dialog.DateTimePicker.SecondLabel"] = "秒",
      ["Everlong.Nester.Dialog.DateTimePicker.Title"] = "选择日期和时间",
      ["Everlong.Nester.Dialog.DateTimePicker.UnlimitedRange"] = "范围：不限",
      ["Everlong.Nester.Dialog.DateTimePicker.YearLabel"] = "年",
      ["Everlong.Nester.Dialog.ImagePreview.BytesSourceDisplayFormat"] = "内存数据（{count} 字节）",
      ["Everlong.Nester.Dialog.ImagePreview.LoadFailedError"] = "图片加载失败",
      ["Everlong.Nester.Dialog.ImagePreview.LoadingStatus"] = "正在加载图片…",
      ["Everlong.Nester.Dialog.ImagePreview.NextText"] = "下一张",
      ["Everlong.Nester.Dialog.ImagePreview.NoHttpClientError"] = "无法加载网络图片：未提供 HttpClient，请通过 ImagePreviewInput.HttpClient 传入。",
      ["Everlong.Nester.Dialog.ImagePreview.PreviousText"] = "上一张",
      ["Everlong.Nester.Dialog.ImagePreview.Title"] = "图片预览",
      ["Everlong.Nester.Dialog.Ipv4.BackspaceToolTip"] = "退格",
      ["Everlong.Nester.Dialog.Ipv4.ClearText"] = "清除",
      ["Everlong.Nester.Dialog.Ipv4.ConfirmText"] = "确认",
      ["Everlong.Nester.Dialog.Ipv4.Message"] = "请输入一个 IPv4 地址",
      ["Everlong.Nester.Dialog.Ipv4.PingBadRouteReason"] = "路由错误",
      ["Everlong.Nester.Dialog.Ipv4.PingFailedFormat"] = "Ping 失败（{reason}）",
      ["Everlong.Nester.Dialog.Ipv4.PingHostUnreachableReason"] = "主机不可达",
      ["Everlong.Nester.Dialog.Ipv4.PingNetworkUnreachableReason"] = "网络不可达",
      ["Everlong.Nester.Dialog.Ipv4.PingPacketTooBigReason"] = "数据包过大",
      ["Everlong.Nester.Dialog.Ipv4.PingPortUnreachableReason"] = "端口不可达",
      ["Everlong.Nester.Dialog.Ipv4.PingProtocolUnreachableReason"] = "协议不可达",
      ["Everlong.Nester.Dialog.Ipv4.PingSuccessFormat"] = "Ping 成功（{time} ms）",
      ["Everlong.Nester.Dialog.Ipv4.PingText"] = "Ping 测试",
      ["Everlong.Nester.Dialog.Ipv4.PingTimedOutReason"] = "已超时",
      ["Everlong.Nester.Dialog.Ipv4.PingTtlExpiredReason"] = "TTL 已过期",
      ["Everlong.Nester.Dialog.Ipv4.PingUnavailableError"] = "Ping 不可用",
      ["Everlong.Nester.Dialog.Ipv4.PingUnknownReason"] = "未知错误",
      ["Everlong.Nester.Dialog.Ipv4.Title"] = "输入 IP 地址",
      ["Everlong.Nester.Dialog.Numpad.BackspaceToolTip"] = "退格",
      ["Everlong.Nester.Dialog.Numpad.ClearToolTip"] = "清空",
      ["Everlong.Nester.Dialog.Numpad.ConfirmText"] = "确认",
      ["Everlong.Nester.Dialog.Numpad.InvalidExpressionError"] = "表达式无效",
      ["Everlong.Nester.Dialog.Numpad.Message"] = "",
      ["Everlong.Nester.Dialog.Numpad.OutOfRangeWarningFormat"] = "结果超出范围：{range}",
      ["Everlong.Nester.Dialog.Numpad.RangeHintFormat"] = "范围：{min} - {max}{step}",
      ["Everlong.Nester.Dialog.Numpad.ResultHintFormat"] = "= {value}{suffix}",
      ["Everlong.Nester.Dialog.Numpad.ResultHintInvalid"] = "= ?",
      ["Everlong.Nester.Dialog.Numpad.Title"] = "输入数字",
      ["Everlong.Nester.Dialog.OptionSelect.Title"] = "请选择",
      ["Everlong.Nester.Dialog.SignaturePad.ClearText"] = "清除",
      ["Everlong.Nester.Dialog.SignaturePad.ConfirmText"] = "确认",
      ["Everlong.Nester.Dialog.SignaturePad.Message"] = "请在下方区域签名以确认",
      ["Everlong.Nester.Dialog.SignaturePad.StrokeCountFormat"] = "已签名笔画：{count}",
      ["Everlong.Nester.Dialog.SignaturePad.Title"] = "签名板",
    });
  }

  private sealed class LangManifestImpl : ILangManifest
  {
    public LangProvider Provider => Lang.Provider;
    public IReadOnlyDictionary<string, IStringProvider> SupportedLocales { get; } =
      new Dictionary<string, IStringProvider>
      {
        ["en"] = Locales.En,
        ["zh-Hans-CN"] = Locales.ZhHansCn,
      };
  }
}

internal sealed class DialogStrings : StringSectionBase
{
  public DialogAlertStrings Alert { get; }
  public DialogConfirmStrings Confirm { get; }
  public DialogChoiceStrings Choice { get; }
  public DialogOptionSelectStrings OptionSelect { get; }
  public DialogNumpadStrings Numpad { get; }
  public DialogColorPickerStrings ColorPicker { get; }
  public DialogDateTimePickerStrings DateTimePicker { get; }
  public DialogImagePreviewStrings ImagePreview { get; }
  public DialogSignaturePadStrings SignaturePad { get; }
  public DialogIpv4Strings Ipv4 { get; }

  internal DialogStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog")
  {
    Alert = new DialogAlertStrings(provider);
    Confirm = new DialogConfirmStrings(provider);
    Choice = new DialogChoiceStrings(provider);
    OptionSelect = new DialogOptionSelectStrings(provider);
    Numpad = new DialogNumpadStrings(provider);
    ColorPicker = new DialogColorPickerStrings(provider);
    DateTimePicker = new DialogDateTimePickerStrings(provider);
    ImagePreview = new DialogImagePreviewStrings(provider);
    SignaturePad = new DialogSignaturePadStrings(provider);
    Ipv4 = new DialogIpv4Strings(provider);
  }

  public string Close => GetString("Close", "Close");
}

internal sealed class DialogAlertStrings : StringSectionBase
{
  internal DialogAlertStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.Alert")
  {
  }

  public string Title => GetString("Title", "Alert");
  public string ButtonText => GetString("ButtonText", "OK");
}

internal sealed class DialogConfirmStrings : StringSectionBase
{
  internal DialogConfirmStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.Confirm")
  {
  }

  public string Title => GetString("Title", "Confirm");
  public string ConfirmText => GetString("ConfirmText", "Yes");
  public string CancelText => GetString("CancelText", "Cancel");
}

internal sealed class DialogChoiceStrings : StringSectionBase
{
  internal DialogChoiceStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.Choice")
  {
  }

  public string Title => GetString("Title", "Choose");
  public string PrimaryText => GetString("PrimaryText", "Yes");
  public string SecondaryText => GetString("SecondaryText", "No");
  public string CancelText => GetString("CancelText", "Cancel");
}

internal sealed class DialogOptionSelectStrings : StringSectionBase
{
  internal DialogOptionSelectStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.OptionSelect")
  {
  }

  public string Title => GetString("Title", "Select");
}

internal sealed class DialogNumpadStrings : StringSectionBase
{
  internal DialogNumpadStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.Numpad")
  {
  }

  public string Title => GetString("Title", "Input number");
  public string Message => GetString("Message", "");
  public string ConfirmText => GetString("ConfirmText", "Confirm");
  public string ClearToolTip => GetString("ClearToolTip", "Clear");
  public string BackspaceToolTip => GetString("BackspaceToolTip", "Backspace");
  public string RangeHint => GetString("RangeHintFormat", "Range: {min} - {max}{step}");
  public string FormatRangeHint(object? min, object? max, object? step) => IcuMessageFormatter.Format(RangeHint, new Dictionary<string, object?> { ["min"] = min, ["max"] = max, ["step"] = step });
  public string ResultHintInvalid => GetString("ResultHintInvalid", "= ?");
  public string ResultHint => GetString("ResultHintFormat", "= {value}{suffix}");
  public string FormatResultHint(object? value, object? suffix) => IcuMessageFormatter.Format(ResultHint, new Dictionary<string, object?> { ["value"] = value, ["suffix"] = suffix });
  public string InvalidExpressionError => GetString("InvalidExpressionError", "Invalid expression");
  public string OutOfRangeWarning => GetString("OutOfRangeWarningFormat", "Result out of range: {range}");
  public string FormatOutOfRangeWarning(object? range) => IcuMessageFormatter.Format(OutOfRangeWarning, new Dictionary<string, object?> { ["range"] = range });
}

internal sealed class DialogColorPickerStrings : StringSectionBase
{
  internal DialogColorPickerStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.ColorPicker")
  {
  }

  public string Title => GetString("Title", "Select Color");
  public string Message => GetString("Message", "Adjust channel values to select a color");
  public string ConfirmText => GetString("ConfirmText", "Confirm");
  public string ResetText => GetString("ResetText", "Reset");
}

internal sealed class DialogDateTimePickerStrings : StringSectionBase
{
  internal DialogDateTimePickerStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.DateTimePicker")
  {
  }

  public string Title => GetString("Title", "Select Date and Time");
  public string Message => GetString("Message", "Enter date and time");
  public string ConfirmText => GetString("ConfirmText", "Confirm");
  public string NowText => GetString("NowText", "Now");
  public string InvalidInput => GetString("InvalidInput", "Invalid date/time input");
  public string UnlimitedRange => GetString("UnlimitedRange", "Range: Unlimited");
  public string RangeHint => GetString("RangeHintFormat", "Range: {min} - {max}");
  public string FormatRangeHint(object? min, object? max) => IcuMessageFormatter.Format(RangeHint, new Dictionary<string, object?> { ["min"] = min, ["max"] = max });
  public string YearLabel => GetString("YearLabel", "Year");
  public string MonthLabel => GetString("MonthLabel", "Month");
  public string DayLabel => GetString("DayLabel", "Day");
  public string HourLabel => GetString("HourLabel", "Hour");
  public string MinuteLabel => GetString("MinuteLabel", "Minute");
  public string SecondLabel => GetString("SecondLabel", "Second");
}

internal sealed class DialogImagePreviewStrings : StringSectionBase
{
  internal DialogImagePreviewStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.ImagePreview")
  {
  }

  public string Title => GetString("Title", "Image Preview");
  public string PreviousText => GetString("PreviousText", "Previous");
  public string NextText => GetString("NextText", "Next");
  public string LoadingStatus => GetString("LoadingStatus", "Loading image...");
  public string LoadFailedError => GetString("LoadFailedError", "Failed to load image");
  public string NoHttpClientError => GetString("NoHttpClientError", "Cannot load network image: HttpClient not provided. Please pass it through ImagePreviewInput.HttpClient.");
  public string BytesSourceDisplay => GetString("BytesSourceDisplayFormat", "Memory Data ({count} bytes)");
  public string FormatBytesSourceDisplay(object? count) => IcuMessageFormatter.Format(BytesSourceDisplay, new Dictionary<string, object?> { ["count"] = count });
}

internal sealed class DialogSignaturePadStrings : StringSectionBase
{
  internal DialogSignaturePadStrings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.SignaturePad")
  {
  }

  public string Title => GetString("Title", "Signature Pad");
  public string Message => GetString("Message", "Please sign in the area below to confirm");
  public string ConfirmText => GetString("ConfirmText", "Confirm");
  public string ClearText => GetString("ClearText", "Clear");
  public string StrokeCount => GetString("StrokeCountFormat", "Signed strokes: {count}");
  public string FormatStrokeCount(object? count) => IcuMessageFormatter.Format(StrokeCount, new Dictionary<string, object?> { ["count"] = count });
}

internal sealed class DialogIpv4Strings : StringSectionBase
{
  internal DialogIpv4Strings(LangProvider provider) : base(provider, "Everlong.Nester.Dialog.Ipv4")
  {
  }

  public string Title => GetString("Title", "Enter IP Address");
  public string Message => GetString("Message", "Please enter an IPv4 address");
  public string ConfirmText => GetString("ConfirmText", "Confirm");
  public string ClearText => GetString("ClearText", "Clear");
  public string PingText => GetString("PingText", "Ping Test");
  public string BackspaceToolTip => GetString("BackspaceToolTip", "Backspace");
  public string PingSuccess => GetString("PingSuccessFormat", "Ping succeeded ({time} ms)");
  public string FormatPingSuccess(object? time) => IcuMessageFormatter.Format(PingSuccess, new Dictionary<string, object?> { ["time"] = time });
  public string PingFailed => GetString("PingFailedFormat", "Ping failed ({reason})");
  public string FormatPingFailed(object? reason) => IcuMessageFormatter.Format(PingFailed, new Dictionary<string, object?> { ["reason"] = reason });
  public string PingUnavailableError => GetString("PingUnavailableError", "Ping unavailable");
  public string PingTimedOutReason => GetString("PingTimedOutReason", "Timed out");
  public string PingHostUnreachableReason => GetString("PingHostUnreachableReason", "Host unreachable");
  public string PingNetworkUnreachableReason => GetString("PingNetworkUnreachableReason", "Network unreachable");
  public string PingProtocolUnreachableReason => GetString("PingProtocolUnreachableReason", "Protocol unreachable");
  public string PingPortUnreachableReason => GetString("PingPortUnreachableReason", "Port unreachable");
  public string PingPacketTooBigReason => GetString("PingPacketTooBigReason", "Packet too big");
  public string PingTtlExpiredReason => GetString("PingTtlExpiredReason", "TTL expired");
  public string PingBadRouteReason => GetString("PingBadRouteReason", "Bad route");
  public string PingUnknownReason => GetString("PingUnknownReason", "Unknown error");
}
