<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Everlong.Nester.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everlong.Nester.Abstractions\Everlong.Nester.Abstractions.csproj" />
  </ItemGroup>

</Project>
