using System.Collections.Immutable;
using Everlong.Nester.Generators.Constants;
using Everlong.Nester.Generators.Extensions;
using Everlong.Nester.Generators.Helpers;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Everlong.Nester.Generators.Models;

/// <summary>
///   Where a generated half goes and the shape it restates: the file-name hint (the trigger's fully
///   qualified metadata name), the namespace, the trigger's own declaration shape and every type
///   enclosing it, innermost first.
/// </summary>
/// <remarks>
///   Built in the transform phase.  The generation phase reads this record and never a symbol, so the
///   pipeline node that produces it stays comparable across compilations and the output node caches.
/// </remarks>
internal sealed record TypeHierarchy(
  string FilenameHint,
  string Namespace,
  TypeShapeInfo Self,
  EquatableArray<TypeShapeInfo> EnclosingTypes)
{
  /// <summary>Reads the hierarchy of the given type.</summary>
  public static TypeHierarchy From(INamedTypeSymbol symbol)
    => new(symbol.GetFullyQualifiedMetadataName(),
           symbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : symbol.ContainingNamespace.ToDisplayString(),
           TypeShapeHelper.ShapeOf(symbol),
           TypeShapeHelper.GetContainingTypes(symbol));

  /// <summary>
  ///   The whole generated file for the trigger's own half: its declaration restated with the given
  ///   members, wrapped in every type enclosing it, in the trigger's namespace.
  /// </summary>
  public CompilationUnitSyntax GetPartialHalf(
    ImmutableArray<string> usings,
    ImmutableArray<MemberDeclarationSyntax> members,
    ImmutableArray<BaseTypeSyntax> baseTypes = default)
  {
    TypeDeclarationSyntax declaration = Self.GetDeclaration();

    if (baseTypes.Length > 0)
    {
      // Roslyn types AddBaseListTypes on BaseTypeDeclarationSyntax; the node is still this declaration.
      declaration = (TypeDeclarationSyntax)declaration.AddBaseListTypes(baseTypes.ToArray());
    }

    MemberDeclarationSyntax root = declaration.AddMembers(members.ToArray());

    foreach (TypeShapeInfo enclosing in EnclosingTypes)
      root = enclosing.GetDeclaration().WithMembers(SingletonList(root));

    return GetCompilationUnit(usings, root);
  }

  /// <summary>
  ///   The whole generated file for a declaration the generator introduces itself — a sibling of the
  ///   trigger, in the trigger's namespace.  Only the namespace and the file coordinates are the
  ///   trigger's; the hierarchy is not restated.
  /// </summary>
  public CompilationUnitSyntax GetCompilationUnit(
    ImmutableArray<string> usings,
    MemberDeclarationSyntax declaration)
  {
    MemberDeclarationSyntax root = string.IsNullOrEmpty(Namespace)
      ? declaration
      : FileScopedNamespaceDeclaration(ParseName(Namespace)).WithMembers(SingletonList(declaration));

    CompilationUnitSyntax unit = CompilationUnit().AddMembers(root);

    if (!usings.IsEmpty)
    {
      unit = unit.AddUsings(usings
        .OrderBy(static nameSpace => nameSpace, StringComparer.Ordinal)
        .Select(static nameSpace => UsingDirective(ParseName(nameSpace)))
        .ToArray());
    }

    // The header leads the compilation unit, and the leading trivia already on its first token is kept:
    // with no namespace and no usings that token is the outermost declaration itself, and its
    // `/// <inheritdoc/>` would otherwise be replaced by the header.
    SyntaxTriviaList leading = unit.GetLeadingTrivia();

    return unit
      .WithLeadingTrivia(ParseLeadingTrivia(Conventions.AutoGeneratedHeader).AddRange(leading))
      .NormalizeWhitespace(indentation: Conventions.Indentation);
  }
}
