using System.Globalization;
using Avalonia.Controls;
using Avalonia.Data.Converters;
using Avalonia;
using Everlong.Nester.Helpers;

namespace Everlong.Nester.Converters;

/// <summary>
/// Converts a notification type enum to a Brush resource.
/// </summary>
/// <remarks>
/// This converter resolves a brush resource from the application's resource dictionary based on the notification type.
/// It uses <see cref="ResourceKeyHelper.GetBrushKey"/> to determine the appropriate resource key for the given type value.
/// 
/// Example usage in XAML:
/// <code>
/// &lt;Border Background="{Binding NotificationType, Converter={StaticResource TypeToBrushConverter}}" /&gt;
/// </code>
/// 
/// The converter expects the application's resource dictionary to contain brush resources with keys
/// generated by <see cref="ResourceKeyHelper.GetBrushKey"/>.
/// If the resource key is not found or null, the converter returns null, allowing the binding to fall back to the default.
/// </remarks>
public sealed class TypeToBrushConverter : IValueConverter
{
  /// <summary>
  /// Converts a notification type value to a Brush resource from the application's resource dictionary.
  /// </summary>
  /// <param name="value">
  /// The notification type to convert.
  /// The converter uses <see cref="ResourceKeyHelper.GetBrushKey"/> to determine the resource key.
  /// </param>
  /// <param name="targetType">The type of the binding target property — <see cref="Avalonia.Media.Brush"/>.</param>
  /// <param name="parameter">Ignored.</param>
  /// <param name="culture">Ignored.</param>
  /// <returns>
  /// The Brush resource corresponding to the notification type, if found in the application's resource dictionary.
  /// Returns <c>null</c> if the resource key cannot be determined or if the resource is not found.
  /// </returns>
  public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
  {
    string? key = ResourceKeyHelper.GetBrushKey(value);

    if (key != null)
    {
      if (Application.Current?.TryGetResource(key, out object? resource) == true)
      {
        return resource;
      }
    }

    // Fallback or default
    return null;
  }

  /// <summary>
  /// Not implemented. This converter does not support reverse conversion.
  /// </summary>
  /// <param name="value">Not used.</param>
  /// <param name="targetType">Not used.</param>
  /// <param name="parameter">Not used.</param>
  /// <param name="culture">Not used.</param>
  /// <returns>Never returns; always throws <see cref="NotImplementedException"/>.</returns>
  /// <exception cref="NotImplementedException">Always thrown as this converter is one-way only.</exception>
  public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
  {
    throw new NotImplementedException();
  }
}
