namespace Everlong.Nester.Generators.Constants;

internal static class Conventions
{
  internal const string ViewSuffix = "View";
  internal const string PageSuffix = "Page";
  internal const string ModelSuffix = "Model";

  internal const string LocatorSuffix = "Locator";
  internal const string Indentation = "  ";

  internal const string GeneratorSuffix = ".g.cs";
  internal const string AutoGeneratedHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

  /// <summary>The generator the emitted code names in its <c>[GeneratedCode]</c> attribute.</summary>
  internal const string GeneratorToolName = "Everlong.Nester.Generators";

  /// <summary>
  ///   The generating assembly's version, stamped into every generated member.  The snapshots scrub it to
  ///   <c>&lt;ASSEMBLY_VERSION&gt;</c>, so a baseline does not move with the package version.
  /// </summary>
  internal static readonly string GeneratorVersion =
    typeof(Conventions).Assembly.GetName().Version?.ToString() ?? string.Empty;

}
