#nullable enable
using System.Collections.Generic;
using Everlong.Globalization;

namespace NesterApp.Properties;

/// <summary>
/// This class was generated by <c>dotnet elg gen</c>.
/// <para>
/// Extends <see cref="Lang"/> with coordinator helpers for multi-assembly locale switching.
/// Call <see cref="Initialize"/> at app startup to register all manifests, then call
/// <see cref="UseLocale"/> whenever the user changes the locale.
/// </para>
/// <para>Do not edit this file manually; it is overwritten on next generation.</para>
/// </summary>
public static partial class Lang
{
  private static LangCoordinator? _coordinator;

  /// <summary>
  /// Creates a <see cref="LangCoordinator"/>, registers all assembly manifests,
  /// and stores the instance. Call this once at app startup before the first
  /// <see cref="UseLocale"/> call.
  /// </summary>
  /// <param name="defaultLocale">The default locale to use.</param>
  public static void Initialize(string? defaultLocale = null)
  {
    var coord = new LangCoordinator();
    coord.Register(Everlong.Nester.Extensions.Properties.Lang.Manifest);
    coord.Register(Manifest);
    _coordinator = coord;
    if (defaultLocale is not null)
      UseLocale(defaultLocale);
  }

  /// <summary>
  /// Switches all registered assemblies to the best available locale match.
  /// When the app supports a locale that an external assembly does not,
  /// the app's string provider is chained as primary over the external assembly's
  /// fallback (collaborative overlay).
  /// </summary>
  public static void UseLocale(string locale)
  {
    _coordinator!.Use(locale);

    // Collaborative overlay for Everlong.Nester.Extensions.Properties.Lang
    ApplyCollaborativeOverlay(Everlong.Nester.Extensions.Properties.Lang.Manifest, locale);
  }

  private static void ApplyCollaborativeOverlay(ILangManifest externalManifest, string locale)
  {
    if (!externalManifest.SupportedLocales.ContainsKey(locale)
        && Manifest.SupportedLocales.TryGetValue(locale, out var appLocale))
    {
      var fallback = LangCoordinator.Resolve(externalManifest.SupportedLocales, locale);
      if (fallback is not null)
        externalManifest.Provider.Use(new ChainedStringProvider(appLocale, fallback));
    }
  }
}
