#nullable enable
using System.Collections.Generic;
using Everlong.Globalization;

namespace NesterApp.Properties;

/// <summary>
/// This class was generated by <c>dotnet elg gen</c>.
/// <para>Usage:</para>
/// <list type="bullet">
/// <item><description>Update strings in the JSON files under locale subdirectories.</description></item>
/// <item><description>Add a locale by creating a new subdirectory (for example <c>zh-CN\</c>) with matching JSON files.</description></item>
/// <item><description>Regenerate by running <c>dotnet elg gen</c> from the project directory.</description></item>
/// <item><description>Configuration file: <c>Properties\i18n\i18n.json</c>.</description></item>
/// <item><description>Do not edit generated files manually; they are overwritten on next generation.</description></item>
/// </list>
/// </summary>
public static partial class Lang
{
  /// <summary>The global language provider for this assembly.</summary>
  public static readonly LangProvider Provider = new(Locales.ZhCn);

  /// <summary>Returns the language manifest describing all supported locales.</summary>
  public static ILangManifest Manifest { get; } = new LangManifestImpl();

  /// <summary>Strings for the <c>Backdrop</c> section.</summary>
  public static BackdropStrings Backdrop { get; } = new BackdropStrings(Provider);
  /// <summary>Strings for the <c>Labs</c> section.</summary>
  public static LabsStrings Labs { get; } = new LabsStrings(Provider);
  /// <summary>Strings for the <c>Login</c> section.</summary>
  public static LoginStrings Login { get; } = new LoginStrings(Provider);
  /// <summary>Strings for the <c>Navigation</c> section.</summary>
  public static NavigationStrings Navigation { get; } = new NavigationStrings(Provider);
  /// <summary>Strings for the <c>Pages</c> section.</summary>
  public static PagesStrings Pages { get; } = new PagesStrings(Provider);
  /// <summary>Strings for the <c>Settings</c> section.</summary>
  public static SettingsStrings Settings { get; } = new SettingsStrings(Provider);
  /// <summary>Strings for the <c>Shell</c> section.</summary>
  public static ShellStrings Shell { get; } = new ShellStrings(Provider);
  /// <summary>Strings for the <c>Workspace</c> section.</summary>
  public static WorkspaceStrings Workspace { get; } = new WorkspaceStrings(Provider);

  private sealed class LangManifestImpl : ILangManifest
  {
    public LangProvider Provider => Lang.Provider;
    public IReadOnlyDictionary<string, IStringProvider> SupportedLocales { get; } =
      new Dictionary<string, IStringProvider>
      {
        ["zh-CN"] = Locales.ZhCn,
        ["en"] = Locales.En,
        ["zh-TW"] = Locales.ZhTw,
      };
  }
}

/// <summary>String section for the <c>Backdrop</c> module.</summary>
public sealed class BackdropStrings : StringSectionBase
{
  internal BackdropStrings(LangProvider provider) : base(provider, "Backdrop")
  {
  }

  /// <summary>背景实验台</summary>
  public string Title => GetString("Title", "背景实验台");
  /// <summary>模式</summary>
  public string Mode => GetString("Mode", "模式");
  /// <summary>微粒</summary>
  public string Motes => GetString("Motes", "微粒");
  /// <summary>光幕</summary>
  public string Veils => GetString("Veils", "光幕");
  /// <summary>速度</summary>
  public string Speed => GetString("Speed", "速度");
  /// <summary>玻璃</summary>
  public string Glass => GetString("Glass", "玻璃");
  /// <summary>视差</summary>
  public string Parallax => GetString("Parallax", "视差");
  /// <summary>暂停</summary>
  public string Pause => GetString("Pause", "暂停");
  /// <summary>重置</summary>
  public string Reset => GetString("Reset", "重置");
}

/// <summary>String section for the <c>Labs</c> module.</summary>
public sealed class LabsStrings : StringSectionBase
{
  internal LabsStrings(LangProvider provider) : base(provider, "Labs")
  {
  }

  /// <summary>Page title</summary>
  public string InteractionLabTitle => GetString("InteractionLabTitle", "交互实验室");
  /// <summary>集中演示 Dialog、Toast、Snackbar、Notification 与内建会话。</summary>
  public string InteractionLabSubtitle => GetString("InteractionLabSubtitle", "集中演示 Dialog、Toast、Snackbar、Notification 与内建会话。");
  /// <summary>通知</summary>
  public string Notifications => GetString("Notifications", "通知");
  /// <summary>消息条</summary>
  public string Snackbars => GetString("Snackbars", "消息条");
  /// <summary>轻提示</summary>
  public string Toasts => GetString("Toasts", "轻提示");
  /// <summary>对话框</summary>
  public string Dialogs => GetString("Dialogs", "对话框");
  /// <summary>映射预览</summary>
  public string MappingPreview => GetString("MappingPreview", "映射预览");
  /// <summary>信息</summary>
  public string Info => GetString("Info", "信息");
  /// <summary>成功</summary>
  public string Success => GetString("Success", "成功");
  /// <summary>警告</summary>
  public string Warning => GetString("Warning", "警告");
  /// <summary>错误</summary>
  public string Error => GetString("Error", "错误");
  /// <summary>简单消息条</summary>
  public string SimpleSnackbar => GetString("SimpleSnackbar", "简单消息条");
  /// <summary>带操作消息条</summary>
  public string ActionSnackbar => GetString("ActionSnackbar", "带操作消息条");
  /// <summary>信息提示</summary>
  public string InfoToast => GetString("InfoToast", "信息提示");
  /// <summary>成功提示</summary>
  public string SuccessToast => GetString("SuccessToast", "成功提示");
  /// <summary>错误提示</summary>
  public string ErrorToast => GetString("ErrorToast", "错误提示");
  /// <summary>警告框</summary>
  public string Alert => GetString("Alert", "警告框");
  /// <summary>确认框</summary>
  public string Confirm => GetString("Confirm", "确认框");
  /// <summary>可延迟确认框</summary>
  public string DeferrableConfirm => GetString("DeferrableConfirm", "可延迟确认框");
  /// <summary>自定义选项</summary>
  public string CustomOptions => GetString("CustomOptions", "自定义选项");
  /// <summary>嵌套对话框</summary>
  public string NestedDialog => GetString("NestedDialog", "嵌套对话框");
  /// <summary>选择选项</summary>
  public string SelectOption => GetString("SelectOption", "选择选项");
  /// <summary>等待</summary>
  public string Wait => GetString("Wait", "等待");
  /// <summary>全局加载</summary>
  public string GlobalLoading => GetString("GlobalLoading", "全局加载");
  /// <summary>数字输入</summary>
  public string InputNumber => GetString("InputNumber", "数字输入");
  /// <summary>签名</summary>
  public string SignName => GetString("SignName", "签名");
  /// <summary>选择颜色</summary>
  public string PickColor => GetString("PickColor", "选择颜色");
  /// <summary>选择日期时间</summary>
  public string PickDatetime => GetString("PickDatetime", "选择日期时间");
  /// <summary>选择 IPv4</summary>
  public string PickIpv4 => GetString("PickIpv4", "选择 IPv4");
  /// <summary>预览图片</summary>
  public string PreviewImage => GetString("PreviewImage", "预览图片");
  /// <summary>导航实验室</summary>
  public string RouteItemLabTitle => GetString("RouteItemLabTitle", "导航实验室");
  /// <summary>实验环境：测试不同场景下的导航高亮方案。</summary>
  public string RouteItemLabSubtitle => GetString("RouteItemLabSubtitle", "实验环境：测试不同场景下的导航高亮方案。");
  /// <summary>Section A - 扁平导航（ItemsControl + RouteLink）</summary>
  public string SectionATitle => GetString("SectionATitle", "Section A - 扁平导航（ItemsControl + RouteLink）");
  /// <summary>框架默认叶子导航视觉：无需手写 DataTemplate。</summary>
  public string SectionADesc => GetString("SectionADesc", "框架默认叶子导航视觉：无需手写 DataTemplate。");
  /// <summary>Section A2 - 扁平导航覆盖（显式提供 RouteLink 内容）</summary>
  public string SectionA2Title => GetString("SectionA2Title", "Section A2 - 扁平导航覆盖（显式提供 RouteLink 内容）");
  /// <summary>用户仍可显式提供内容，覆盖默认显示。</summary>
  public string SectionA2Desc => GetString("SectionA2Desc", "用户仍可显式提供内容，覆盖默认显示。");
  /// <summary>Section B - 树形导航（RouteTreeControl）</summary>
  public string SectionBTitle => GetString("SectionBTitle", "Section B - 树形导航（RouteTreeControl）");
  /// <summary>树形导航：RouteTreeControl + RouteTreeItem 递归渲染，每个 Item 自治管理激活状态。</summary>
  public string SectionBDesc1 => GetString("SectionBDesc1", "树形导航：RouteTreeControl + RouteTreeItem 递归渲染，每个 Item 自治管理激活状态。");
  /// <summary>'Main' 是纯分组（无路由），点击只展开/折叠。</summary>
  public string SectionBDesc2 => GetString("SectionBDesc2", "'Main' 是纯分组（无路由），点击只展开/折叠。");
  /// <summary>'Settings' 是可导航分组，点击导航，子项激活时自动展开。</summary>
  public string SectionBDesc3 => GetString("SectionBDesc3", "'Settings' 是可导航分组，点击导航，子项激活时自动展开。");
  /// <summary>Section C - 纯树控件（通用树，无导航语义）</summary>
  public string SectionCTitle => GetString("SectionCTitle", "Section C - 纯树控件（通用树，无导航语义）");
  /// <summary>TreeControl + TreeItem：地位等同平台 TreeView / TreeViewItem，但去掉选择语义。</summary>
  public string SectionCDesc1 => GetString("SectionCDesc1", "TreeControl + TreeItem：地位等同平台 TreeView / TreeViewItem，但去掉选择语义。");
  /// <summary>通过 TreeDataTemplate 递归渲染任意 POCO 树节点，点击可展开/折叠，与导航无关。</summary>
  public string SectionCDesc2 => GetString("SectionCDesc2", "通过 TreeDataTemplate 递归渲染任意 POCO 树节点，点击可展开/折叠，与导航无关。");
  /// <summary>Section D - 自定义图标（Pattern B：SvgIcon + DataTemplate）</summary>
  public string SectionDTitle => GetString("SectionDTitle", "Section D - 自定义图标（Pattern B：SvgIcon + DataTemplate）");
  /// <summary>Icon 属性赋值为普通 C# record（SvgIcon），XAML 中注册对应 DataTemplate。</summary>
  public string SectionDDesc1 => GetString("SectionDDesc1", "Icon 属性赋值为普通 C# record（SvgIcon），XAML 中注册对应 DataTemplate。");
  /// <summary>ViewModel 对 UI 零依赖；换图标库只需替换 DataTemplate 和 Converter，不改 ViewModel。</summary>
  public string SectionDDesc2 => GetString("SectionDDesc2", "ViewModel 对 UI 零依赖；换图标库只需替换 DataTemplate 和 Converter，不改 ViewModel。");
  /// <summary>占位菜单 1</summary>
  public string PlaceholderMenu1 => GetString("PlaceholderMenu1", "占位菜单 1");
  /// <summary>占位菜单 2</summary>
  public string PlaceholderMenu2 => GetString("PlaceholderMenu2", "占位菜单 2");
  /// <summary>占位菜单 3</summary>
  public string PlaceholderMenu3 => GetString("PlaceholderMenu3", "占位菜单 3");
  /// <summary>TextView：普通映射文本内容。</summary>
  public string MappingTextMessage => GetString("MappingTextMessage", "TextView：普通映射文本内容。");
  /// <summary>Nester 头像</summary>
  public string MappingImageAlt => GetString("MappingImageAlt", "Nester 头像");
  /// <summary>通过 AlertMessage 映射到 AlertView。</summary>
  public string MappingAlertWarningMessage => GetString("MappingAlertWarningMessage", "通过 AlertMessage 映射到 AlertView。");
  /// <summary>通过映射显示错误级别提醒。</summary>
  public string MappingAlertErrorMessage => GetString("MappingAlertErrorMessage", "通过映射显示错误级别提醒。");
  /// <summary>信息通知。</summary>
  public string InfoNotificationMessage => GetString("InfoNotificationMessage", "信息通知。");
  /// <summary>操作已完成。</summary>
  public string SuccessNotificationMessage => GetString("SuccessNotificationMessage", "操作已完成。");
  /// <summary>输入无效。</summary>
  public string WarningNotificationMessage => GetString("WarningNotificationMessage", "输入无效。");
  /// <summary>发生错误。</summary>
  public string ErrorNotificationMessage => GetString("ErrorNotificationMessage", "发生错误。");
  /// <summary>简单消息条消息</summary>
  public string SimpleSnackbarMessage => GetString("SimpleSnackbarMessage", "简单消息条消息");
  /// <summary>文件已删除</summary>
  public string ActionSnackbarMessage => GetString("ActionSnackbarMessage", "文件已删除");
  /// <summary>撤销</summary>
  public string ActionSnackbarUndo => GetString("ActionSnackbarUndo", "撤销");
  /// <summary>已点击撤销！</summary>
  public string ActionSnackbarUndoClickedMessage => GetString("ActionSnackbarUndoClickedMessage", "已点击撤销！");
  /// <summary>这是一条信息提示</summary>
  public string InfoToastMessage => GetString("InfoToastMessage", "这是一条信息提示");
  /// <summary>操作成功完成</summary>
  public string SuccessToastMessage => GetString("SuccessToastMessage", "操作成功完成");
  /// <summary>发生了一些问题</summary>
  public string ErrorToastMessage => GetString("ErrorToastMessage", "发生了一些问题");
  /// <summary>这是一个简单的警告对话框。</summary>
  public string AlertDialogMessage => GetString("AlertDialogMessage", "这是一个简单的警告对话框。");
  /// <summary>你要继续吗？</summary>
  public string ConfirmDialogMessage => GetString("ConfirmDialogMessage", "你要继续吗？");
  /// <summary>确认</summary>
  public string ConfirmDialogTitle => GetString("ConfirmDialogTitle", "确认");
  /// <summary>已确认！</summary>
  public string ConfirmDialogAcceptedMessage => GetString("ConfirmDialogAcceptedMessage", "已确认！");
  /// <summary>已取消</summary>
  public string ConfirmDialogCanceledMessage => GetString("ConfirmDialogCanceledMessage", "已取消");
  /// <summary>此对话框已启用点击空白关闭，点击外部即可关闭。</summary>
  public string CustomOptionsDialogMessage => GetString("CustomOptionsDialogMessage", "此对话框已启用点击空白关闭，点击外部即可关闭。");
  /// <summary>这是一个支持嵌套能力的自定义对话框</summary>
  public string NestedDialogMessage => GetString("NestedDialogMessage", "这是一个支持嵌套能力的自定义对话框");
  /// <summary>选项 1</summary>
  public string SelectionOption1 => GetString("SelectionOption1", "选项 1");
  /// <summary>选项 2</summary>
  public string SelectionOption2 => GetString("SelectionOption2", "选项 2");
  /// <summary>选项 3</summary>
  public string SelectionOption3 => GetString("SelectionOption3", "选项 3");
  /// <summary>请选择一个选项</summary>
  public string SelectionPrompt => GetString("SelectionPrompt", "请选择一个选项");
  /// <summary>选择</summary>
  public string SelectionTitle => GetString("SelectionTitle", "选择");
  /// <summary>你选择了：{option}</summary>
  public string SelectionResultMessage => GetString("SelectionResultMessage", "你选择了：{option}");
  /// <summary>Formats <see cref="SelectionResultMessage"/>.</summary>
  public string FormatSelectionResultMessage(object? option) => IcuMessageFormatter.Format(SelectionResultMessage, new Dictionary<string, object?> { ["option"] = option });
  /// <summary>请选择形状</summary>
  public string ShapeSelectionPrompt => GetString("ShapeSelectionPrompt", "请选择形状");
  /// <summary>形状选择</summary>
  public string ShapeSelectionTitle => GetString("ShapeSelectionTitle", "形状选择");
  /// <summary>你选择了圆形</summary>
  public string ShapeSelectedCircleMessage => GetString("ShapeSelectedCircleMessage", "你选择了圆形");
  /// <summary>你选择了矩形</summary>
  public string ShapeSelectedRectangleMessage => GetString("ShapeSelectedRectangleMessage", "你选择了矩形");
  /// <summary>请稍候</summary>
  public string WaitDialogTitle => GetString("WaitDialogTitle", "请稍候");
  /// <summary>处理中...</summary>
  public string WaitDialogMessage => GetString("WaitDialogMessage", "处理中...");
  /// <summary>即将完成...</summary>
  public string WaitDialogProgressMessage => GetString("WaitDialogProgressMessage", "即将完成...");
  /// <summary>输入重量</summary>
  public string InputWeightTitle => GetString("InputWeightTitle", "输入重量");
  /// <summary>重量</summary>
  public string InputWeightMessage => GetString("InputWeightMessage", "重量");
  /// <summary>kg</summary>
  public string InputWeightUnit => GetString("InputWeightUnit", "kg");
  /// <summary>加载中…</summary>
  public string Loading => GetString("Loading", "加载中…");
  /// <summary>正在播放…</summary>
  public string NowPlaying => GetString("NowPlaying", "正在播放…");
  /// <summary>ICU MessageFormat</summary>
  public string IcuSectionTitle => GetString("IcuSectionTitle", "ICU MessageFormat");
  /// <summary>演示 {name} 插值、{count, plural, ...} 复数和 {gender, select, ...} 选择语法。</summary>
  public string IcuSectionDesc => GetString("IcuSectionDesc", "演示 {name} 插值、{count, plural, ...} 复数和 {gender, select, ...} 选择语法。");
  /// <summary>Formats <see cref="IcuSectionDesc"/>.</summary>
  public string FormatIcuSectionDesc(object? name, object? count, object? gender) => IcuMessageFormatter.Format(IcuSectionDesc, new Dictionary<string, object?> { ["name"] = name, ["count"] = count, ["gender"] = gender });
  /// <summary>插值：</summary>
  public string IcuInterpolationLabel => GetString("IcuInterpolationLabel", "插值：");
  /// <summary>换名字</summary>
  public string IcuChangeName => GetString("IcuChangeName", "换名字");
  /// <summary>你好，{name}！</summary>
  public string IcuInterpolationResult => GetString("IcuInterpolationResult", "你好，{name}！");
  /// <summary>Formats <see cref="IcuInterpolationResult"/>.</summary>
  public string FormatIcuInterpolationResult(object? name) => IcuMessageFormatter.Format(IcuInterpolationResult, new Dictionary<string, object?> { ["name"] = name });
  /// <summary>复数：</summary>
  public string IcuPluralLabel => GetString("IcuPluralLabel", "复数：");
  /// <summary>增加</summary>
  public string IcuAddItem => GetString("IcuAddItem", "增加");
  /// <summary>减少</summary>
  public string IcuRemoveItem => GetString("IcuRemoveItem", "减少");
  /// <summary>{count, plural, =0 {空空如也} =1 {1 个项目} other {{count} 个项目}}</summary>
  public string IcuPluralResult => GetString("IcuPluralResult", "{count, plural, =0 {空空如也} =1 {1 个项目} other {{count} 个项目}}");
  /// <summary>Formats <see cref="IcuPluralResult"/>.</summary>
  public string FormatIcuPluralResult(object? count) => IcuMessageFormatter.Format(IcuPluralResult, new Dictionary<string, object?> { ["count"] = count });
  /// <summary>选择：</summary>
  public string IcuSelectLabel => GetString("IcuSelectLabel", "选择：");
  /// <summary>切换性别</summary>
  public string IcuCycleGender => GetString("IcuCycleGender", "切换性别");
  /// <summary>{gender, select, male {他写的示例} female {她写的示例} other {TA 写的示例}}</summary>
  public string IcuSelectResult => GetString("IcuSelectResult", "{gender, select, male {他写的示例} female {她写的示例} other {TA 写的示例}}");
  /// <summary>Formats <see cref="IcuSelectResult"/>.</summary>
  public string FormatIcuSelectResult(object? gender) => IcuMessageFormatter.Format(IcuSelectResult, new Dictionary<string, object?> { ["gender"] = gender });
  /// <summary>强制</summary>
  public string Mandatory => GetString("Mandatory", "强制");
  /// <summary>非强制</summary>
  public string NonMandatory => GetString("NonMandatory", "非强制");
  /// <summary>左侧抽屉</summary>
  public string LeftDrawer => GetString("LeftDrawer", "左侧抽屉");
  /// <summary>确定要继续吗？</summary>
  public string DeferrableConfirmMessage => GetString("DeferrableConfirmMessage", "确定要继续吗？");
  /// <summary>你在 5 秒后点击了“是”</summary>
  public string DeferrableConfirmAccepted => GetString("DeferrableConfirmAccepted", "你在 5 秒后点击了“是”");
  /// <summary>自定义对话框</summary>
  public string CustomDialogTitle => GetString("CustomDialogTitle", "自定义对话框");
  /// <summary>是</summary>
  public string DialogYes => GetString("DialogYes", "是");
  /// <summary>否</summary>
  public string DialogNo => GetString("DialogNo", "否");
  /// <summary>嵌套</summary>
  public string DialogNested => GetString("DialogNested", "嵌套");
  /// <summary>确定</summary>
  public string DialogOk => GetString("DialogOk", "确定");
  /// <summary>关闭</summary>
  public string DialogClose => GetString("DialogClose", "关闭");
  /// <summary>从左侧滑入，高度与壳一致。</summary>
  public string LeftDrawerBody1 => GetString("LeftDrawerBody1", "从左侧滑入，高度与壳一致。");
  /// <summary>点击遮罩层关闭（轻关闭）。</summary>
  public string LeftDrawerBody2 => GetString("LeftDrawerBody2", "点击遮罩层关闭（轻关闭）。");
  /// <summary>演示对话框</summary>
  public string DemoDialogTitle => GetString("DemoDialogTitle", "演示对话框");
}

/// <summary>String section for the <c>Login</c> module.</summary>
public sealed class LoginStrings : StringSectionBase
{
  internal LoginStrings(LangProvider provider) : base(provider, "Login")
  {
  }

  /// <summary>登录</summary>
  public string Title => GetString("Title", "登录");
  /// <summary>欢迎回来</summary>
  public string WelcomeHeading => GetString("WelcomeHeading", "欢迎回来");
  /// <summary>用户名（admin/user）</summary>
  public string UsernameLabel => GetString("UsernameLabel", "用户名（admin/user）");
  /// <summary>用户名</summary>
  public string UsernameWatermark => GetString("UsernameWatermark", "用户名");
  /// <summary>密码（任意）</summary>
  public string PasswordLabel => GetString("PasswordLabel", "密码（任意）");
  /// <summary>密码</summary>
  public string PasswordWatermark => GetString("PasswordWatermark", "密码");
  /// <summary>登录</summary>
  public string SignInButton => GetString("SignInButton", "登录");
  /// <summary>管理员</summary>
  public string AdminButton => GetString("AdminButton", "管理员");
  /// <summary>普通用户</summary>
  public string UserButton => GetString("UserButton", "普通用户");
  /// <summary>凭据无效，请输入 'admin' 或 'user'。</summary>
  public string InvalidCredentials => GetString("InvalidCredentials", "凭据无效，请输入 'admin' 或 'user'。");
}

/// <summary>String section for the <c>Navigation</c> module.</summary>
public sealed class NavigationStrings : StringSectionBase
{
  internal NavigationStrings(LangProvider provider) : base(provider, "Navigation")
  {
  }

  /// <summary>退出登录</summary>
  public string Logout => GetString("Logout", "退出登录");
  /// <summary>主菜单</summary>
  public string Main => GetString("Main", "主菜单");
  /// <summary>首页</summary>
  public string Landing => GetString("Landing", "首页");
  /// <summary>交互实验室</summary>
  public string InteractionLab => GetString("InteractionLab", "交互实验室");
  /// <summary>文章</summary>
  public string Posts => GetString("Posts", "文章");
  /// <summary>设置</summary>
  public string Settings => GetString("Settings", "设置");
  /// <summary>通用</summary>
  public string General => GetString("General", "通用");
  /// <summary>账户</summary>
  public string Account => GetString("Account", "账户");
  /// <summary>安全</summary>
  public string Security => GetString("Security", "安全");
  /// <summary>个人资料</summary>
  public string Profile => GetString("Profile", "个人资料");
  /// <summary>管理面板</summary>
  public string AdminPanel => GetString("AdminPanel", "管理面板");
  /// <summary>导航实验室</summary>
  public string RouteItemLab => GetString("RouteItemLab", "导航实验室");
  /// <summary>视频播放器</summary>
  public string VideoPlayer => GetString("VideoPlayer", "视频播放器");
  /// <summary>后退</summary>
  public string Back => GetString("Back", "后退");
  /// <summary>前进</summary>
  public string Forward => GetString("Forward", "前进");
  /// <summary>最小化</summary>
  public string Minimize => GetString("Minimize", "最小化");
  /// <summary>最大化</summary>
  public string Maximize => GetString("Maximize", "最大化");
  /// <summary>关闭</summary>
  public string Close => GetString("Close", "关闭");
  /// <summary>背景面板</summary>
  public string BackdropPanel => GetString("BackdropPanel", "背景面板");
}

/// <summary>String section for the <c>Pages</c> module.</summary>
public sealed class PagesStrings : StringSectionBase
{
  internal PagesStrings(LangProvider provider) : base(provider, "Pages")
  {
  }

  /// <summary>Nester 功能中心</summary>
  public string DashboardTitle => GetString("DashboardTitle", "Nester 功能中心");
  /// <summary>这个首页聚焦能力地图，具体交互拆分到独立实验页。</summary>
  public string DashboardSubtitle => GetString("DashboardSubtitle", "这个首页聚焦能力地图，具体交互拆分到独立实验页。");
  /// <summary>🧭 导航与布局</summary>
  public string Feature1Title => GetString("Feature1Title", "🧭 导航与布局");
  /// <summary>MainLayout + SettingsLayout + 强类型路由</summary>
  public string Feature1Desc => GetString("Feature1Desc", "MainLayout + SettingsLayout + 强类型路由");
  /// <summary>⚡ 生命周期与到达</summary>
  public string Feature2Title => GetString("Feature2Title", "⚡ 生命周期与到达");
  /// <summary>Posts 的 IArrived 生命周期与详情路由参数</summary>
  public string Feature2Desc => GetString("Feature2Desc", "Posts 的 IArrived 生命周期与详情路由参数");
  /// <summary>🔐 授权与守卫</summary>
  public string Feature3Title => GetString("Feature3Title", "🔐 授权与守卫");
  /// <summary>Admin 策略授权 + Profile 离开确认</summary>
  public string Feature3Desc => GetString("Feature3Desc", "Admin 策略授权 + Profile 离开确认");
  /// <summary>按场景进入演示</summary>
  public string EntryHeader => GetString("EntryHeader", "按场景进入演示");
  /// <summary>交互实验室</summary>
  public string OpenInteractionLab => GetString("OpenInteractionLab", "交互实验室");
  /// <summary>文章与路由参数</summary>
  public string OpenPosts => GetString("OpenPosts", "文章与路由参数");
  /// <summary>个人资料守卫</summary>
  public string OpenProfile => GetString("OpenProfile", "个人资料守卫");
  /// <summary>嵌套设置</summary>
  public string OpenSettings => GetString("OpenSettings", "嵌套设置");
  /// <summary>管理员授权</summary>
  public string OpenAdmin => GetString("OpenAdmin", "管理员授权");
  /// <summary>用户资料</summary>
  public string ProfileTitle => GetString("ProfileTitle", "用户资料");
  /// <summary>管理面板（需授权）</summary>
  public string AdminTitle => GetString("AdminTitle", "管理面板（需授权）");
  /// <summary>文章</summary>
  public string PostsTitle => GetString("PostsTitle", "文章");
  /// <summary>查看详情</summary>
  public string ViewDetail => GetString("ViewDetail", "查看详情");
  /// <summary>在浮层中打开</summary>
  public string OpenInFloat => GetString("OpenInFloat", "在浮层中打开");
  /// <summary>评论</summary>
  public string Comments => GetString("Comments", "评论");
  /// <summary>设置</summary>
  public string SettingsHeader => GetString("SettingsHeader", "设置");
  /// <summary>账户设置</summary>
  public string AccountTitle => GetString("AccountTitle", "账户设置");
  /// <summary>更改会自动保存。</summary>
  public string ChangesSubtitle => GetString("ChangesSubtitle", "更改会自动保存。");
  /// <summary>个人资料</summary>
  public string ProfileSection => GetString("ProfileSection", "个人资料");
  /// <summary>显示名称</summary>
  public string DisplayNameWatermark => GetString("DisplayNameWatermark", "显示名称");
  /// <summary>隐私</summary>
  public string PrivacySection => GetString("PrivacySection", "隐私");
  /// <summary>允许他人发现我的资料</summary>
  public string AllowProfileDiscovery => GetString("AllowProfileDiscovery", "允许他人发现我的资料");
  /// <summary>隐藏活动详情</summary>
  public string HideActivityDetails => GetString("HideActivityDetails", "隐藏活动详情");
  /// <summary>删除账户</summary>
  public string DeleteAccount => GetString("DeleteAccount", "删除账户");
  /// <summary>安全设置</summary>
  public string SecurityTitle => GetString("SecurityTitle", "安全设置");
  /// <summary>要求双重身份验证</summary>
  public string RequireTwoFactor => GetString("RequireTwoFactor", "要求双重身份验证");
  /// <summary>在不活跃时自动锁定</summary>
  public string AutoLock => GetString("AutoLock", "在不活跃时自动锁定");
  /// <summary>会话超时（分钟，5–120）</summary>
  public string SessionTimeoutLabel => GetString("SessionTimeoutLabel", "会话超时（分钟，5–120）");
  /// <summary>显示名称</summary>
  public string ProfileDisplayName => GetString("ProfileDisplayName", "显示名称");
  /// <summary>个人简介</summary>
  public string ProfileBio => GetString("ProfileBio", "个人简介");
  /// <summary>保存</summary>
  public string Save => GetString("Save", "保存");
  /// <summary>取消</summary>
  public string Cancel => GetString("Cancel", "取消");
  /// <summary>导航守卫</summary>
  public string NavigationGuardTitle => GetString("NavigationGuardTitle", "导航守卫");
  /// <summary>试着在下面的输入框里输入内容，然后离开本页——你会被拦截。</summary>
  public string NavigationGuardMessage => GetString("NavigationGuardMessage", "试着在下面的输入框里输入内容，然后离开本页——你会被拦截。");
  /// <summary>你能看到此页面，是因为你拥有 'Admin' 角色。</summary>
  public string AdminViewingReason => GetString("AdminViewingReason", "你能看到此页面，是因为你拥有 'Admin' 角色。");
  /// <summary>执行管理操作</summary>
  public string AdminAction => GetString("AdminAction", "执行管理操作");
  /// <summary>你没有权限查看此页面。</summary>
  public string NoPermission => GetString("NoPermission", "你没有权限查看此页面。");
  /// <summary>文章详情</summary>
  public string PostDetailChromeTitle => GetString("PostDetailChromeTitle", "文章详情");
  /// <summary>你有未保存的更改。确定要离开吗？</summary>
  public string ProfileLeaveConfirmMessage => GetString("ProfileLeaveConfirmMessage", "你有未保存的更改。确定要离开吗？");
  /// <summary>是</summary>
  public string ProfileLeaveConfirmYes => GetString("ProfileLeaveConfirmYes", "是");
  /// <summary>留下</summary>
  public string ProfileLeaveConfirmStay => GetString("ProfileLeaveConfirmStay", "留下");
  /// <summary>会话即将结束</summary>
  public string SessionEndingTitle => GetString("SessionEndingTitle", "会话即将结束");
  /// <summary>系统正在结束会话。关闭首页吗？</summary>
  public string SessionEndingMessage => GetString("SessionEndingMessage", "系统正在结束会话。关闭首页吗？");
}

/// <summary>String section for the <c>Settings</c> module.</summary>
public sealed class SettingsStrings : StringSectionBase
{
  internal SettingsStrings(LangProvider provider) : base(provider, "Settings")
  {
  }

  /// <summary>通用设置</summary>
  public string Title => GetString("Title", "通用设置");
  /// <summary>更改会自动保存。</summary>
  public string Subtitle => GetString("Subtitle", "更改会自动保存。");
  /// <summary>语言</summary>
  public string LocaleLabel => GetString("LocaleLabel", "语言");
  /// <summary>英文</summary>
  public string SwitchToEnglish => GetString("SwitchToEnglish", "英文");
  /// <summary>简体中文</summary>
  public string SwitchToChinese => GetString("SwitchToChinese", "简体中文");
  /// <summary>繁体中文</summary>
  public string SwitchToTraditionalChinese => GetString("SwitchToTraditionalChinese", "繁体中文");
  /// <summary>外观</summary>
  public string AppearanceLabel => GetString("AppearanceLabel", "外观");
  /// <summary>主题</summary>
  public string ThemeLabel => GetString("ThemeLabel", "主题");
  /// <summary>跟随系统</summary>
  public string ThemeSystem => GetString("ThemeSystem", "跟随系统");
  /// <summary>浅色</summary>
  public string ThemeLight => GetString("ThemeLight", "浅色");
  /// <summary>深色</summary>
  public string ThemeDark => GetString("ThemeDark", "深色");
  /// <summary>自动保存更改</summary>
  public string AutoSave => GetString("AutoSave", "自动保存更改");
  /// <summary>字体大小（10–24）</summary>
  public string FontSizeLabel => GetString("FontSizeLabel", "字体大小（10–24）");
  /// <summary>重启以查看完整的语言切换?</summary>
  public string RestartConfirmMessage => GetString("RestartConfirmMessage", "重启以查看完整的语言切换?");
  /// <summary>提醒</summary>
  public string RestartConfirmTitle => GetString("RestartConfirmTitle", "提醒");
  /// <summary>例如 en、zh-CN</summary>
  public string LanguageWatermark => GetString("LanguageWatermark", "例如 en、zh-CN");
}

/// <summary>String section for the <c>Shell</c> module.</summary>
public sealed class ShellStrings : StringSectionBase
{
  internal ShellStrings(LangProvider provider) : base(provider, "Shell")
  {
  }

  /// <summary>NesterApp</summary>
  public string WindowTitle => GetString("WindowTitle", "NesterApp");
  /// <summary>确定要关闭此窗口吗？</summary>
  public string CloseConfirmMessage => GetString("CloseConfirmMessage", "确定要关闭此窗口吗？");
  /// <summary>是，关闭</summary>
  public string CloseConfirmYes => GetString("CloseConfirmYes", "是，关闭");
  /// <summary>否，留下</summary>
  public string CloseConfirmNo => GetString("CloseConfirmNo", "否，留下");
  /// <summary>启动参数</summary>
  public string ActivationStartupArgs => GetString("ActivationStartupArgs", "启动参数");
  /// <summary>{count, plural, =0 {没有文件} other {{count} 个文件}}</summary>
  public string ActivationFileCount => GetString("ActivationFileCountFormat", "{count, plural, =0 {没有文件} other {{count} 个文件}}");
  /// <summary>Formats <see cref="ActivationFileCount"/>.</summary>
  public string FormatActivationFileCount(object? count) => IcuMessageFormatter.Format(ActivationFileCount, new Dictionary<string, object?> { ["count"] = count });
  /// <summary>另一个实例请求当前实例处理：{summary}。在此处处理吗？</summary>
  public string ActivationRequest => GetString("ActivationRequestFormat", "另一个实例请求当前实例处理：{summary}。在此处处理吗？");
  /// <summary>Formats <see cref="ActivationRequest"/>.</summary>
  public string FormatActivationRequest(object? summary) => IcuMessageFormatter.Format(ActivationRequest, new Dictionary<string, object?> { ["summary"] = summary });
  /// <summary>在此处理</summary>
  public string ActivationAccept => GetString("ActivationAccept", "在此处理");
  /// <summary>在新窗口打开</summary>
  public string ActivationDecline => GetString("ActivationDecline", "在新窗口打开");
  /// <summary>未授权</summary>
  public string Unauthorized => GetString("Unauthorized", "未授权");
}

/// <summary>String section for the <c>Workspace</c> module.</summary>
public sealed class WorkspaceStrings : StringSectionBase
{
  internal WorkspaceStrings(LangProvider provider) : base(provider, "Workspace")
  {
  }

  /// <summary>The session's title</summary>
  public string Title => GetString("Title", "命令面板");
  /// <summary>搜索工作区文件</summary>
  public string Watermark => GetString("Watermark", "搜索工作区文件");
  /// <summary>没有匹配的文件</summary>
  public string Empty => GetString("Empty", "没有匹配的文件");
  /// <summary>回车打开文件 · Esc 关闭</summary>
  public string Hint => GetString("Hint", "回车打开文件 · Esc 关闭");
  /// <summary>{count} 个文件 · {source}</summary>
  public string Watching => GetString("WatchingFormat", "{count} 个文件 · {source}");
  /// <summary>Formats <see cref="Watching"/>.</summary>
  public string FormatWatching(object? count, object? source) => IcuMessageFormatter.Format(Watching, new Dictionary<string, object?> { ["count"] = count, ["source"] = source });
  /// <summary>git 根目录</summary>
  public string SourceGit => GetString("SourceGit", "git 根目录");
  /// <summary>项目目录</summary>
  public string SourceProject => GetString("SourceProject", "项目目录");
  /// <summary>下载目录</summary>
  public string SourceDownloads => GetString("SourceDownloads", "下载目录");
  /// <summary>当前目录</summary>
  public string SourceCurrent => GetString("SourceCurrent", "当前目录");
  /// <summary>无法打开 {path}</summary>
  public string OpenFailed => GetString("OpenFailedFormat", "无法打开 {path}");
  /// <summary>Formats <see cref="OpenFailed"/>.</summary>
  public string FormatOpenFailed(object? path) => IcuMessageFormatter.Format(OpenFailed, new Dictionary<string, object?> { ["path"] = path });
  /// <summary>快捷键提示：Ctrl+Shift+P</summary>
  public string LandingHint => GetString("LandingHint", "快捷键提示：Ctrl+Shift+P");
  /// <summary>打开工作区面板：列出被监控的每个文件，输入即过滤；回车用系统默认程序打开（当前实现仅 Windows）。</summary>
  public string LandingHintNote => GetString("LandingHintNote", "打开工作区面板：列出被监控的每个文件，输入即过滤；回车用系统默认程序打开（当前实现仅 Windows）。");
}
