<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\NesterVersion.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsPackable>false</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <RootNamespace>Everlong.Nester.Generators</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Everlong.Nester.Generators.Tests" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Remove="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>

</Project>
